[package]
name = "dorker"
version = "0.0.0"
authors = ["?"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.0", features = ["blocking"] }
select = "0.4.3"
clap = "2.33.0"
rusqlite = "0.21.0"
structopt = "0.3.7"
futures = "0.3.1"
